-- Upgrade Suggestions to private player/admin conversations
alter table public.suggestions add column if not exists category text not null default 'Suggestion';
alter table public.suggestions add column if not exists status text not null default 'new';
alter table public.suggestions add column if not exists updated_at timestamptz not null default now();
alter table public.suggestions enable row level security;
drop policy if exists "suggestions own read" on public.suggestions;
drop policy if exists "suggestions own insert" on public.suggestions;
drop policy if exists "suggestions own update" on public.suggestions;
create policy "suggestions own read" on public.suggestions for select to authenticated using ((select auth.uid())=user_id or (select public.is_admin()));
create policy "suggestions own insert" on public.suggestions for insert to authenticated with check ((select auth.uid())=user_id);
create policy "suggestions own update" on public.suggestions for update to authenticated using ((select auth.uid())=user_id or (select public.is_admin())) with check ((select auth.uid())=user_id or (select public.is_admin()));
grant select,insert,update on public.suggestions to authenticated;

create table if not exists public.suggestion_messages (
  id bigint generated by default as identity primary key,
  suggestion_id bigint not null references public.suggestions(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  message text not null check(char_length(message) between 1 and 2000),
  created_at timestamptz not null default now(),
  read_at timestamptz
);
alter table public.suggestion_messages enable row level security;
drop policy if exists "suggestion messages conversation read" on public.suggestion_messages;
drop policy if exists "suggestion messages conversation insert" on public.suggestion_messages;
drop policy if exists "suggestion messages conversation update" on public.suggestion_messages;
create policy "suggestion messages conversation read" on public.suggestion_messages for select to authenticated using (exists(select 1 from public.suggestions s where s.id=suggestion_id and (s.user_id=(select auth.uid()) or (select public.is_admin()))));
create policy "suggestion messages conversation insert" on public.suggestion_messages for insert to authenticated with check (sender_id=(select auth.uid()) and exists(select 1 from public.suggestions s where s.id=suggestion_id and (s.user_id=(select auth.uid()) or (select public.is_admin()))));
create policy "suggestion messages conversation update" on public.suggestion_messages for update to authenticated using (exists(select 1 from public.suggestions s where s.id=suggestion_id and (s.user_id=(select auth.uid()) or (select public.is_admin())))) with check (exists(select 1 from public.suggestions s where s.id=suggestion_id and (s.user_id=(select auth.uid()) or (select public.is_admin()))));
grant select,insert,update on public.suggestion_messages to authenticated;
grant usage,select on sequence public.suggestion_messages_id_seq to authenticated;
