-- Kestrel Court Manager: shared account/player foundation
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text,
  is_admin boolean not null default false,
  requested_player_type text check (requested_player_type in ('permanent','dropin')),
  player_type text check (player_type in ('permanent','dropin')),
  player_type_status text not null default 'pending' check (player_type_status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sports (
  id bigint generated by default as identity primary key,
  name text unique not null check (name in ('badminton','volleyball'))
);

create table if not exists public.player_sports (
  user_id uuid references public.profiles(id) on delete cascade,
  sport_id bigint references public.sports(id) on delete cascade,
  primary key (user_id,sport_id)
);

insert into public.sports(name) values ('badminton'),('volleyball')
on conflict (name) do nothing;

alter table public.profiles enable row level security;
alter table public.player_sports enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and is_admin=true); $$;

create policy "profiles_self_read" on public.profiles for select using (id=auth.uid() or public.is_admin());
create policy "profiles_self_insert" on public.profiles for insert with check (id=auth.uid());
create policy "profiles_self_update" on public.profiles for update using (id=auth.uid() or public.is_admin()) with check (id=auth.uid() or public.is_admin());

create policy "player_sports_self_read" on public.player_sports for select using (user_id=auth.uid() or public.is_admin());
create policy "player_sports_self_insert" on public.player_sports for insert with check (user_id=auth.uid() or public.is_admin());
create policy "player_sports_admin_update" on public.player_sports for update using (public.is_admin()) with check (public.is_admin());
create policy "player_sports_self_delete" on public.player_sports for delete using (user_id=auth.uid() or public.is_admin());

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.profiles(id,full_name,email,requested_player_type,player_type_status)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name','New Player'),
    new.email,
    new.raw_user_meta_data->>'requested_player_type',
    'pending'
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();