-- Kestrel Court Manager: shared account/player foundation
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text,
  is_admin boolean not null default false,
  requested_player_type text check (requested_player_type in ('permanent','dropin')),
  player_type text check (player_type in ('permanent','dropin')),
  player_type_status text not null default 'pending' check (player_type_status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sports (
  id bigint generated by default as identity primary key,
  name text unique not null check (name in ('badminton','volleyball'))
);

create table if not exists public.player_sports (
  user_id uuid references public.profiles(id) on delete cascade,
  sport_id bigint references public.sports(id) on delete cascade,
  primary key (user_id,sport_id)
);

insert into public.sports(name) values ('badminton'),('volleyball')
on conflict (name) do nothing;

alter table public.profiles enable row level security;
alter table public.player_sports enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and is_admin=true); $$;

create policy "profiles_self_read" on public.profiles for select using (id=auth.uid() or public.is_admin());
create policy "profiles_self_insert" on public.profiles for insert with check (id=auth.uid());
create policy "profiles_self_update" on public.profiles for update using (id=auth.uid() or public.is_admin()) with check (id=auth.uid() or public.is_admin());

create policy "player_sports_self_read" on public.player_sports for select using (user_id=auth.uid() or public.is_admin());
create policy "player_sports_self_insert" on public.player_sports for insert with check (user_id=auth.uid() or public.is_admin());
create policy "player_sports_admin_update" on public.player_sports for update using (public.is_admin()) with check (public.is_admin());
create policy "player_sports_self_delete" on public.player_sports for delete using (user_id=auth.uid() or public.is_admin());

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.profiles(id,full_name,email,requested_player_type,player_type_status)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name','New Player'),
    new.email,
    new.raw_user_meta_data->>'requested_player_type',
    'pending'
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Kestrel Court Manager complete database schema
create table if not exists public.locations(id bigint generated by default as identity primary key,name text not null unique,address text,city text,created_at timestamptz default now());
create table if not exists public.sessions(id bigint generated by default as identity primary key,sport_id bigint references public.sports(id),location_id bigint references public.locations(id),session_date date not null,start_time time not null,end_time time not null,capacity int not null default 18,price numeric(10,2) default 0,payment_email text,payment_first boolean default false,registration_open_at timestamptz,registration_deadline timestamptz,payment_deadline timestamptz,status text default 'open' check(status in('open','full','closed')),created_at timestamptz default now());
create table if not exists public.permanent_assignments(user_id uuid references public.profiles(id) on delete cascade,session_id bigint references public.sessions(id) on delete cascade,primary key(user_id,session_id));
create table if not exists public.registrations(id bigint generated by default as identity primary key,user_id uuid references public.profiles(id) on delete cascade,session_id bigint references public.sessions(id) on delete cascade,status text default 'pending' check(status in('pending','confirmed','waitlist','cancelled')),payment_status text default 'unpaid' check(payment_status in('unpaid','paid','removed')),registered_at timestamptz default now(),unique(user_id,session_id));
create table if not exists public.absences(id bigint generated by default as identity primary key,user_id uuid references public.profiles(id) on delete cascade,session_id bigint references public.sessions(id) on delete cascade,not_coming boolean not null default true,created_at timestamptz default now(),unique(user_id,session_id));
create table if not exists public.payments(id bigint generated by default as identity primary key,user_id uuid references public.profiles(id) on delete cascade,session_id bigint references public.sessions(id) on delete cascade,amount numeric(10,2) not null,payment_status text default 'unpaid' check(payment_status in('unpaid','paid')),paid_at timestamptz,notes text,unique(user_id,session_id));
create table if not exists public.communications(id bigint generated by default as identity primary key,title text not null,message text not null,is_pinned boolean default false,is_archived boolean default false,created_by uuid references public.profiles(id),created_at timestamptz default now());
alter table public.locations enable row level security; alter table public.sessions enable row level security; alter table public.permanent_assignments enable row level security; alter table public.registrations enable row level security; alter table public.absences enable row level security; alter table public.payments enable row level security; alter table public.communications enable row level security;
create policy "locations_read_auth" on public.locations for select using(auth.uid() is not null);
create policy "locations_admin" on public.locations for all using(public.is_admin()) with check(public.is_admin());
create policy "sessions_read_auth" on public.sessions for select using(auth.uid() is not null);
create policy "sessions_admin" on public.sessions for all using(public.is_admin()) with check(public.is_admin());
create policy "assignments_read" on public.permanent_assignments for select using(user_id=auth.uid() or public.is_admin());
create policy "assignments_admin" on public.permanent_assignments for all using(public.is_admin()) with check(public.is_admin());
create policy "registrations_own_read" on public.registrations for select using(user_id=auth.uid() or public.is_admin());
create policy "registrations_own_insert" on public.registrations for insert with check(user_id=auth.uid());
create policy "registrations_own_update" on public.registrations for update using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
create policy "registrations_admin" on public.registrations for delete using(public.is_admin());
create policy "absences_own" on public.absences for select using(user_id=auth.uid() or public.is_admin());
create policy "absences_insert" on public.absences for insert with check(user_id=auth.uid());
create policy "absences_update" on public.absences for update using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
create policy "absences_admin_delete" on public.absences for delete using(public.is_admin());
create policy "payments_read" on public.payments for select using(user_id=auth.uid() or public.is_admin());
create policy "payments_admin" on public.payments for all using(public.is_admin()) with check(public.is_admin());
create policy "communications_read" on public.communications for select using(auth.uid() is not null and is_archived=false);
create policy "communications_admin" on public.communications for all using(public.is_admin()) with check(public.is_admin());

-- Migration policy: players imported from the existing club roster are permanent.
-- Do not delete their existing registration/history. Import the existing users first,
-- then use the admin migration statement below to approve them as permanent.
-- This intentionally does not auto-promote newly registered users.


create table if not exists public.legacy_player_roster (
  id bigint generated by default as identity primary key,
  full_name text not null unique,
  player_type text not null default 'permanent' check (player_type='permanent'),
  migration_status text not null default 'pending_link' check (migration_status in ('pending_link','linked')),
  linked_user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.legacy_player_roster enable row level security;
create policy "legacy roster admin only" on public.legacy_player_roster for all using (public.is_admin()) with check (public.is_admin());
