-- Kestrel Court Manager: shared account/player foundation
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text,
  is_admin boolean not null default false,
  requested_player_type text check (requested_player_type in ('permanent','dropin')),
  player_type text check (player_type in ('permanent','dropin')),
  player_type_status text not null default 'pending' check (player_type_status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sports (
  id bigint generated by default as identity primary key,
  name text unique not null check (name in ('badminton','volleyball'))
);

create table if not exists public.player_sports (
  user_id uuid references public.profiles(id) on delete cascade,
  sport_id bigint references public.sports(id) on delete cascade,
  primary key (user_id,sport_id)
);

insert into public.sports(name) values ('badminton'),('volleyball')
on conflict (name) do nothing;

alter table public.profiles enable row level security;
alter table public.player_sports enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and is_admin=true); $$;

create policy "profiles_self_read" on public.profiles for select using (id=auth.uid() or public.is_admin());
create policy "profiles_self_insert" on public.profiles for insert with check (id=auth.uid());
create policy "profiles_self_update" on public.profiles for update using (id=auth.uid() or public.is_admin()) with check (id=auth.uid() or public.is_admin());

create policy "player_sports_self_read" on public.player_sports for select using (user_id=auth.uid() or public.is_admin());
create policy "player_sports_self_insert" on public.player_sports for insert with check (user_id=auth.uid() or public.is_admin());
create policy "player_sports_admin_update" on public.player_sports for update using (public.is_admin()) with check (public.is_admin());
create policy "player_sports_self_delete" on public.player_sports for delete using (user_id=auth.uid() or public.is_admin());

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.profiles(id,full_name,email,requested_player_type,player_type_status)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name','New Player'),
    new.email,
    new.raw_user_meta_data->>'requested_player_type',
    'pending'
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Kestrel Court Manager complete database schema
create table if not exists public.locations(id bigint generated by default as identity primary key,name text not null unique,address text,city text,created_at timestamptz default now());
create table if not exists public.sessions(id bigint generated by default as identity primary key,sport_id bigint references public.sports(id),location_id bigint references public.locations(id),session_date date not null,start_time time not null,end_time time not null,capacity int not null default 18,price numeric(10,2) default 0,payment_email text,payment_first boolean default false,registration_open_at timestamptz,registration_deadline timestamptz,payment_deadline timestamptz,status text default 'open' check(status in('open','full','closed')),created_at timestamptz default now());
create table if not exists public.permanent_assignments(user_id uuid references public.profiles(id) on delete cascade,session_id bigint references public.sessions(id) on delete cascade,primary key(user_id,session_id));
create table if not exists public.registrations(id bigint generated by default as identity primary key,user_id uuid references public.profiles(id) on delete cascade,session_id bigint references public.sessions(id) on delete cascade,status text default 'pending' check(status in('pending','confirmed','waitlist','cancelled')),payment_status text default 'unpaid' check(payment_status in('unpaid','paid','removed')),registered_at timestamptz default now(),unique(user_id,session_id));
create table if not exists public.absences(id bigint generated by default as identity primary key,user_id uuid references public.profiles(id) on delete cascade,session_id bigint references public.sessions(id) on delete cascade,not_coming boolean not null default true,created_at timestamptz default now(),unique(user_id,session_id));
create table if not exists public.payments(id bigint generated by default as identity primary key,user_id uuid references public.profiles(id) on delete cascade,session_id bigint references public.sessions(id) on delete cascade,amount numeric(10,2) not null,payment_status text default 'unpaid' check(payment_status in('unpaid','paid')),paid_at timestamptz,notes text,unique(user_id,session_id));
create table if not exists public.communications(id bigint generated by default as identity primary key,title text not null,message text not null,is_pinned boolean default false,is_archived boolean default false,created_by uuid references public.profiles(id),created_at timestamptz default now());
alter table public.locations enable row level security; alter table public.sessions enable row level security; alter table public.permanent_assignments enable row level security; alter table public.registrations enable row level security; alter table public.absences enable row level security; alter table public.payments enable row level security; alter table public.communications enable row level security;
create policy "locations_read_auth" on public.locations for select using(auth.uid() is not null);
create policy "locations_admin" on public.locations for all using(public.is_admin()) with check(public.is_admin());
create policy "sessions_read_auth" on public.sessions for select using(auth.uid() is not null);
create policy "sessions_admin" on public.sessions for all using(public.is_admin()) with check(public.is_admin());
create policy "assignments_read" on public.permanent_assignments for select using(user_id=auth.uid() or public.is_admin());
create policy "assignments_admin" on public.permanent_assignments for all using(public.is_admin()) with check(public.is_admin());
create policy "registrations_own_read" on public.registrations for select using(user_id=auth.uid() or public.is_admin());
create policy "registrations_own_insert" on public.registrations for insert with check(user_id=auth.uid());
create policy "registrations_own_update" on public.registrations for update using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
create policy "registrations_admin" on public.registrations for delete using(public.is_admin());
create policy "absences_own" on public.absences for select using(user_id=auth.uid() or public.is_admin());
create policy "absences_insert" on public.absences for insert with check(user_id=auth.uid());
create policy "absences_update" on public.absences for update using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
create policy "absences_admin_delete" on public.absences for delete using(public.is_admin());
create policy "payments_read" on public.payments for select using(user_id=auth.uid() or public.is_admin());
create policy "payments_admin" on public.payments for all using(public.is_admin()) with check(public.is_admin());
create policy "communications_read" on public.communications for select using(auth.uid() is not null and is_archived=false);
create policy "communications_admin" on public.communications for all using(public.is_admin()) with check(public.is_admin());

-- Migration policy: players imported from the existing club roster are permanent.
-- Do not delete their existing registration/history. Import the existing users first,
-- then use the admin migration statement below to approve them as permanent.
-- This intentionally does not auto-promote newly registered users.


create table if not exists public.legacy_player_roster (
  id bigint generated by default as identity primary key,
  full_name text not null unique,
  player_type text not null default 'permanent' check (player_type='permanent'),
  migration_status text not null default 'pending_link' check (migration_status in ('pending_link','linked')),
  linked_user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.legacy_player_roster enable row level security;
create policy "legacy roster admin only" on public.legacy_player_roster for all using (public.is_admin()) with check (public.is_admin());


-- Secure registration and absence workflows
create or replace function public.register_dropin(p_session_id bigint)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare
  ptype text; s public.sessions%rowtype; confirmed_count integer;
begin
  select player_type into ptype from public.profiles where id=auth.uid();
  if ptype <> 'dropin' then raise exception 'Only approved drop-in players can register for drop-in sessions'; end if;
  select * into s from public.sessions where id=p_session_id;
  if not found then raise exception 'Session not found'; end if;
  if s.status='closed' then raise exception 'Registration is closed'; end if;
  if s.registration_open_at is not null and now() < s.registration_open_at then raise exception 'Registration is not open yet'; end if;
  if s.registration_deadline is not null and now() > s.registration_deadline then raise exception 'Registration deadline has passed'; end if;
  if exists(select 1 from public.registrations where user_id=auth.uid() and session_id=p_session_id and status in ('pending','confirmed','waitlist')) then
    return 'already_registered';
  end if;
  select count(*) into confirmed_count from public.registrations where session_id=p_session_id and status='confirmed';
  if confirmed_count >= s.capacity then
    insert into public.registrations(user_id,session_id,status,payment_status) values(auth.uid(),p_session_id,'waitlist','unpaid')
    on conflict(user_id,session_id) do update set status='waitlist',payment_status='unpaid';
    return 'waitlist';
  end if;
  insert into public.registrations(user_id,session_id,status,payment_status)
  values(auth.uid(),p_session_id,case when s.payment_first then 'pending' else 'pending' end,'unpaid')
  on conflict(user_id,session_id) do update set status='pending',payment_status='unpaid';
  return 'pending';
end;
$$;

create or replace function public.set_my_absence(p_session_id bigint,p_not_coming boolean)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.profiles where id=auth.uid() and player_type='permanent' and player_type_status='approved') then
    raise exception 'Only approved permanent players can mark absences';
  end if;
  insert into public.absences(user_id,session_id,not_coming)
  values(auth.uid(),p_session_id,p_not_coming)
  on conflict(user_id,session_id) do update set not_coming=excluded.not_coming;
  if p_not_coming then
    update public.registrations set status='cancelled' where user_id=auth.uid() and session_id=p_session_id and status in ('confirmed','pending');
  else
    update public.registrations set status='confirmed',payment_status='paid'
    where user_id=auth.uid() and session_id=p_session_id;
  end if;
end;
$$;

grant execute on function public.register_dropin(bigint) to authenticated;
grant execute on function public.set_my_absence(bigint,boolean) to authenticated;

-- Keep ordinary players from inserting registrations for other users or editing another user's status.
drop policy if exists "registrations_own_insert" on public.registrations;
create policy "registrations_own_insert" on public.registrations for insert
with check (user_id=auth.uid() and exists(select 1 from public.profiles p where p.id=auth.uid() and p.player_type='dropin' and p.player_type_status='approved'));

drop policy if exists "registrations_own_update" on public.registrations;
create policy "registrations_own_update" on public.registrations for update
using (user_id=auth.uid() or public.is_admin())
with check (public.is_admin() or (user_id=auth.uid() and status in ('cancelled','pending','waitlist')));


-- Prevent non-admin users from changing their own approval/type.
create or replace function public.prevent_player_type_self_change()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is not null and auth.uid() = old.id and not public.is_admin() then
    new.player_type := old.player_type;
    new.player_type_status := old.player_type_status;
    new.requested_player_type := old.requested_player_type;
    new.is_admin := old.is_admin;
  end if;
  return new;
end;
$$;
drop trigger if exists protect_player_type on public.profiles;
create trigger protect_player_type before update on public.profiles
for each row execute function public.prevent_player_type_self_change();

drop policy if exists "registrations_own_update" on public.registrations;
drop policy if exists "registrations_own_insert" on public.registrations;
create policy "registrations_dropin_insert" on public.registrations for insert
with check (user_id=auth.uid() and exists(select 1 from public.profiles p where p.id=auth.uid() and p.player_type='dropin' and p.player_type_status='approved'));
drop policy if exists "absences_insert" on public.absences;
drop policy if exists "absences_update" on public.absences;


-- Permanent registration choices: each approved permanent player can request
-- multiple regular location/time/court entries. Admin approval creates the roster entry.
alter table public.sessions add column if not exists court text not null default 'Court 1';

create table if not exists public.permanent_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_id bigint not null references public.sessions(id) on delete cascade,
  court text not null default 'Court 1',
  status text not null default 'pending' check(status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  unique(user_id,session_id)
);

alter table public.permanent_requests enable row level security;

drop policy if exists "permanent_requests_self_read" on public.permanent_requests;
create policy "permanent_requests_self_read" on public.permanent_requests
for select using(user_id=auth.uid() or public.is_admin());

drop policy if exists "permanent_requests_self_insert" on public.permanent_requests;
create policy "permanent_requests_self_insert" on public.permanent_requests
for insert with check(
  user_id=auth.uid()
  and exists(select 1 from public.profiles p where p.id=auth.uid() and p.player_type='permanent' and p.player_type_status='approved')
);

drop policy if exists "permanent_requests_admin_update" on public.permanent_requests;
create policy "permanent_requests_admin_update" on public.permanent_requests
for update using(public.is_admin()) with check(public.is_admin());

drop policy if exists "permanent_requests_admin_delete" on public.permanent_requests;
create policy "permanent_requests_admin_delete" on public.permanent_requests
for delete using(public.is_admin());

create or replace function public.approve_permanent_request(p_request_id bigint)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare r public.permanent_requests%rowtype;
begin
  if not public.is_admin() then raise exception 'Only administrators can approve permanent registrations'; end if;
  select * into r from public.permanent_requests where id=p_request_id and status='pending' for update;
  if not found then raise exception 'Permanent request not found or already reviewed'; end if;

  update public.permanent_requests
    set status='approved', reviewed_at=now()
    where id=r.id;

  insert into public.permanent_assignments(user_id,session_id)
    values(r.user_id,r.session_id)
    on conflict(user_id,session_id) do nothing;

  insert into public.registrations(user_id,session_id,status,payment_status)
    values(r.user_id,r.session_id,'confirmed','paid')
    on conflict(user_id,session_id) do update
      set status='confirmed', payment_status='paid';
end;
$$;

grant execute on function public.approve_permanent_request(bigint) to authenticated;


-- Allow administrators to update registration approvals/payment status.
drop policy if exists "registrations_admin_update" on public.registrations;
create policy "registrations_admin_update" on public.registrations
for update using(public.is_admin()) with check(public.is_admin());


-- Full 2026-2027 spreadsheet allocation support
create table if not exists public.recurring_schedules (
  id bigint generated by default as identity primary key,
  source_key text unique not null,
  sport_id bigint references public.sports(id),
  location_id bigint references public.locations(id),
  weekday text not null,
  schedule_label text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.legacy_court_allocations (
  id bigint generated by default as identity primary key,
  recurring_schedule_id bigint not null references public.recurring_schedules(id) on delete cascade,
  court text not null,
  player_name text not null,
  source_sheet text,
  source_row int,
);

alter table public.recurring_schedules enable row level security;
alter table public.legacy_court_allocations enable row level security;

drop policy if exists "recurring schedules read auth" on public.recurring_schedules;
create policy "recurring schedules read auth" on public.recurring_schedules
for select to authenticated using (true);

drop policy if exists "recurring schedules admin" on public.recurring_schedules;
create policy "recurring schedules admin" on public.recurring_schedules
for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "legacy allocations admin" on public.legacy_court_allocations;
create policy "legacy allocations admin" on public.legacy_court_allocations
for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

grant select on public.recurring_schedules to authenticated;
grant select,insert,update,delete on public.legacy_court_allocations to authenticated;
grant insert,update,delete on public.recurring_schedules to authenticated;
grant usage,select on sequence public.recurring_schedules_id_seq to authenticated;
grant usage,select on sequence public.legacy_court_allocations_id_seq to authenticated;


-- Recurring permanent-player choices
create table if not exists public.recurring_permanent_requests (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 recurring_schedule_id bigint not null references public.recurring_schedules(id) on delete cascade,
 court text not null,
 status text not null default 'pending' check(status in ('pending','approved','rejected')),
 created_at timestamptz not null default now(),
 reviewed_at timestamptz,
 unique(user_id,recurring_schedule_id)
);
alter table public.recurring_permanent_requests enable row level security;
create policy "recurring perm own read" on public.recurring_permanent_requests for select to authenticated using ((select auth.uid())=user_id or (select public.is_admin()));
create policy "recurring perm own insert" on public.recurring_permanent_requests for insert to authenticated with check ((select auth.uid())=user_id and exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.player_type='permanent' and p.player_type_status='approved'));
create policy "recurring perm own update" on public.recurring_permanent_requests for update to authenticated using ((select auth.uid())=user_id or (select public.is_admin())) with check ((select auth.uid())=user_id or (select public.is_admin()));
grant select,insert,update on public.recurring_permanent_requests to authenticated;
grant usage,select on sequence public.recurring_permanent_requests_id_seq to authenticated;


-- Connect recurring schedules to generated dated sessions
alter table public.recurring_schedules add column if not exists start_time time;
alter table public.recurring_schedules add column if not exists end_time time;
alter table public.sessions add column if not exists recurring_schedule_id bigint references public.recurring_schedules(id);
create unique index if not exists sessions_recurring_date_court_uq on public.sessions(recurring_schedule_id,session_date,court) where recurring_schedule_id is not null;
