import{useEffect,useState}from'react';import{supabase}from'./lib/supabase';
type Screen='home'|'register'|'login'|'pending'|'dashboard';type PlayerType='permanent'|'dropin';type Sport='badminton'|'volleyball';
export default function App(){const[screen,setScreen]=useState<Screen>('home');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[name,setName]=useState('');const[type,setType]=useState<PlayerType>('permanent');const[sports,setSports]=useState<Sport[]>(['badminton']);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[profile,setProfile]=useState<any>(null);
useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session)loadProfile(data.session.user.id)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{if(s)loadProfile(s.user.id)});return()=>data.subscription.unsubscribe()},[]);
async function loadProfile(id:string){const{data}=await supabase.from('profiles').select('*').eq('id',id).single();setProfile(data);setScreen(data?.is_admin?'dashboard':data?.player_type_status==='approved'?'home':'pending')}
function toggleSport(s:Sport){setSports(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s])}
async function register(){setBusy(true);setMessage('');const{data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name,requested_player_type:type}}});if(error){setMessage(error.message);setBusy(false);return}if(data.user){await supabase.from('profiles').update({full_name:name,email,requested_player_type:type}).eq('id',data.user.id);const{data:ids}=await supabase.from('sports').select('id,name').in('name',sports);if(ids?.length)await supabase.from('player_sports').insert(ids.map(x=>({user_id:data.user!.id,sport_id:x.id})))}setScreen('pending');setBusy(false)}
async function login(){setBusy(true);setMessage('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message);setBusy(false)}async function logout(){await supabase.auth.signOut();setProfile(null);setScreen('home')}
const nav=<header><div><div className="brand">🏸 Kestrel Court Manager</div><div className="sub">Badminton & Volleyball</div></div>{profile?<button className="outline" onClick={logout}>Sign out</button>:<button className="outline" onClick={()=>setScreen('login')}>Sign in</button>}</header>;
if(screen==='register')return<><>{nav}</><main><section className="card form"><h2>Create your account</h2><label>Full name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><h3>Sports</h3><div className="tabs"><button className={sports.includes('badminton')?'active':''} onClick={()=>toggleSport('badminton')}>🏸 Badminton</button><button className={sports.includes('volleyball')?'active':''} onClick={()=>toggleSport('volleyball')}>🏐 Volleyball</button></div><h3>Player type request</h3><div className="choice"><button className={type==='permanent'?'active':''} onClick={()=>setType('permanent')}>Permanent Player</button><button className={type==='dropin'?'active':''} onClick={()=>setType('dropin')}>Drop-in Player</button></div><p className="muted">An administrator must approve your requested player type. Only an administrator can change it later.</p>{message&&<p className="error">{message}</p>}<button disabled={busy||!name||!email||password.length<6||sports.length===0} onClick={register}>{busy?'Creating…':'Create account'}</button><button className="link" onClick={()=>setScreen('login')}>Already have an account? Sign in</button></section></main></>;
if(screen==='login')return<><>{nav}</><main><section className="card form"><h2>Sign in</h2><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{message&&<p className="error">{message}</p>}<button disabled={busy} onClick={login}>{busy?'Signing in…':'Sign in'}</button><button className="link" onClick={()=>setScreen('register')}>Create a new account</button></section></main></>;
if(screen==='pending')return<><>{nav}</><main><section className="card center"><div className="big">⏳</div><h2>Account awaiting approval</h2><p>Your account was created successfully.</p><p>Your requested player type is <strong>{profile?.requested_player_type||type}</strong>.</p><p className="muted">An administrator must approve your player type before you can use player features.</p></section></main></>;
if(screen==='dashboard')return <AdminDashboard profile={profile} onLogout={logout}/>;
if(profile?.player_type_status==='approved')return <PlayerHome profile={profile} onLogout={logout}/>;
return<><>{nav}</><main><section className="hero"><span className="pill">NEW INDEPENDENT VERSION</span><h1>Manage players, courts and sessions in one place.</h1><p>Mobile-friendly and designed for Kestrel sports activities.</p><div className="actions"><button onClick={()=>setScreen('register')}>Create account</button><button className="outline" onClick={()=>setScreen('login')}>Sign in</button></div></section><section className="card"><h2>One account. Two sports.</h2><p className="muted">Your account can participate in badminton, volleyball, or both. Player type is shared across both sports and controlled by an administrator.</p></section></main><footer>© 2026 Kestrel Court Manager</footer></>}


function PlayerHome({profile,onLogout}:{profile:any,onLogout:()=>void}){
 const[sessions,setSessions]=useState<any[]>([]);const[absences,setAbsences]=useState<Record<string,boolean>>({});const[msg,setMsg]=useState('');
 useEffect(()=>{(async()=>{const{data}=await supabase.from('sessions').select('id,session_date,start_time,end_time,capacity,price,sports(name),locations(name,address)').gte('session_date',new Date().toISOString().slice(0,10)).order('session_date').limit(50);setSessions(data||[]);const{data:a}=await supabase.from('absences').select('session_id,not_coming').eq('user_id',profile.id);setAbsences(Object.fromEntries((a||[]).map((x:any)=>[x.session_id,x.not_coming])));})();},[profile.id]);
 async function notComing(id:string){setMsg('');const{error}=await supabase.from('absences').upsert({user_id:profile.id,session_id:id,not_coming:true},{onConflict:'user_id,session_id'});if(error)setMsg(error.message);else setAbsences(v=>({...v,[id]:true}));}
 return <><header><div><div className="brand">🏸 Kestrel Court Manager</div><div className="sub">{profile.full_name} · {profile.player_type==='permanent'?'Permanent Player':'Drop-in Player'}</div></div><button className="outline" onClick={onLogout}>Sign out</button></header><main><section className="card"><h2>My upcoming sessions</h2><p className="muted">{profile.player_type==='permanent'?'You are registered as a permanent player. You can mark yourself Not Coming for a specific session.':'Drop-in registration is available for sessions with open spots.'}</p>{msg&&<p className="error">{msg}</p>}{sessions.map(s=><div className="session-row" key={s.id}><div><strong>{s.session_date}</strong><div>{s.sports?.name} · {s.locations?.name}</div><div className="muted">{s.start_time}–{s.end_time} · ${s.price}</div></div>{profile.player_type==='permanent'&&!absences[s.id]&&<button onClick={()=>notComing(s.id)}>Not Coming</button>}{profile.player_type==='permanent'&&absences[s.id]&&<span className="success">Marked Not Coming</span>}</div>)}{!sessions.length&&<p className="muted">No upcoming sessions found.</p>}</section></main></>;
}

function AdminDashboard({profile,onLogout}:{profile:any,onLogout:()=>void}){
 const[players,setPlayers]=useState<any[]>([]);const[legacy,setLegacy]=useState<any[]>([]);const[msg,setMsg]=useState('');
 async function load(){const[p,l]=await Promise.all([supabase.from('profiles').select('*').order('full_name'),supabase.from('legacy_player_roster').select('*').order('full_name')]);setPlayers(p.data||[]);setLegacy(l.data||[]);}
 useEffect(()=>{load()},[]);
 async function approve(id:string,type:'permanent'|'dropin'){const{error}=await supabase.from('profiles').update({player_type:type,player_type_status:'approved',requested_player_type:type}).eq('id',id);if(error)setMsg(error.message);else load();}
 async function link(id:number,userId:string){const{error}=await supabase.from('legacy_player_roster').update({linked_user_id:userId,migration_status:'linked'}).eq('id',id);if(error)setMsg(error.message);else{await supabase.from('profiles').update({player_type:'permanent',player_type_status:'approved',requested_player_type:'permanent'}).eq('id',userId);load();}}
 return <><header><div><div className="brand">🏸 Kestrel Court Manager · Admin</div><div className="sub">{profile.full_name}</div></div><button className="outline" onClick={onLogout}>Sign out</button></header><main><section className="card"><h2>Player approvals</h2>{msg&&<p className="error">{msg}</p>}{players.filter(p=>!p.is_admin).map(p=><div className="player-row" key={p.id}><div><strong>{p.full_name||p.email}</strong><div className="muted">{p.email} · {p.player_type_status||'pending'} · requested {p.requested_player_type||'—'}</div></div>{p.player_type_status!=='approved'?<button onClick={()=>approve(p.id,p.requested_player_type||'permanent')}>Approve {p.requested_player_type||'permanent'}</button>:<select value={p.player_type||'permanent'} onChange={e=>approve(p.id,e.target.value as PlayerType)}><option value="permanent">Permanent</option><option value="dropin">Drop-in</option></select>}</div>)}</section><section className="card"><h2>Existing players — permanent</h2><p className="muted">These names are preserved from the existing roster. Link them to a new account after that player creates an account.</p>{legacy.map(l=><div className="player-row" key={l.id}><div><strong>{l.full_name}</strong><div className="muted">{l.migration_status==='linked'?'Linked':'Waiting for account'}</div></div>{l.migration_status==='linked'?<span className="success">Permanent</span>:<span className="muted">Link from player account</span>}</div>)}</section></main></>;
}
